<?php

class UploadController extends BaseController
{

    /**
     * Action name
     * @var string
     */
    protected $bootstrap = '<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">';
    protected $style = "light";
    protected $rankName = [];
    protected $rankColor = [];
    public $name = 'index';

    /**
     * @var UserProfile
     */
    protected $UP;

    public function __construct(UserProfile $UserProfile)
    {
        $this->UP = $UserProfile;
        require_once './lang/ru/rankConfig.php';
        $tmpClass = new rankConfig();
        $this->rankColor = $tmpClass->getRankColor();
        $this->rankName = $tmpClass->getRankName();
    }

    protected function makeRankArray($inArray = [])
    {
        return parent::makeRankArray($inArray);
    }

    protected function redirect($url)
    {
        return parent::redirect($url); // TODO: Change the autogenerated stub
    }

    public function upSeminarsFormAction(Request $request)
    {
        return new Response(
            $this->render(
                'upload/form/seminarUpload', [
                'title' => 'Upload file',
                'bs' => $this->bootstrap,
                'style' => $this->style,
                'error' => "You don't have permission"
            ])
        );
    }

    public function uploadConfirmAction(Request $request)
    {
        move_uploaded_file($_FILES['excelFile']['tmp_name'], 'upload/excel/testname');
        return new Response(
            $this->render(
                'template', [
                'title' => 'upload seminar',
                'bs' => $this->bootstrap,
                'style' => $this->style,
            ])
        );
    }
}