<?php

class UploadController extends BaseController
{

    /**
     * Action name
     * @var string
     */
    protected $bootstrap = '<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">';
    protected $style = "light";
    protected $rankName = [];
    protected $rankColor = [];
    protected $statusCode = [];
    public $name = 'index';

    /**
     * @var UserProfile
     */
    protected $UP;

    public function __construct(UploadProfile $uploadProfile)
    {
        $this->UP = $uploadProfile;
        require_once './lang/ru/rankConfig.php';
        $tmpClass = new rankConfig();
        $this->rankColor = $tmpClass->getRankColor();
        $this->rankName = $tmpClass->getRankName();
        $this->statusCode = $tmpClass->getStatusCode();
    }

    protected function makeRankArray($inArray = [])
    {
        return parent::makeRankArray($inArray);
    }

    protected function redirect($url)
    {
        return parent::redirect($url); // TODO: Change the autogenerated stub
    }

    public function upSeminarsFormAction(Request $request)
    {
        $seminarUpload = $this->UP->getUploadSeminar();
        $users = $this->UP->takeUser();
        return new Response(
            $this->render(
                'upload/form/seminarUpload', [
                'title' => 'Upload file',
                'bs' => $this->bootstrap,
                'style' => $this->style,
                'semUploads' => $seminarUpload,
                'users' => $users,
                'statusCode' => $this->statusCode,
            ])
        );
    }

    public function uploadConfirmAction(Request $request)
    {
        $date = time();
        $name = 'Seminar'.$date.'.xls';
        move_uploaded_file($_FILES['excelFile']['tmp_name'], 'upload/excel/'.$name);
        $desc = $request->getRequestParameter('uploadExcel_desc');
        $this->UP->uploadAddLogs($_COOKIE['pAccount'], $date, $_FILES['excelFile']['size'], $desc, $name);
        return new Response(
            $this->render(
                'template', [
                'title' => 'upload seminar',
                'bs' => $this->bootstrap,
                'style' => $this->style,
            ])
        );
    }

    public function searchSemByIdAction(Request $request)
    {
        $id = $request->getQueryParameter('semID');
        $user = $this->UP->takeUserById($id);
        if($this->UP->checkId($id))
        {
            $seminar = $this->UP->getSeminarById($id);
            return new Response(
                $this->render(
                    'upload/sembyId', [
                    'title' => 'seminars #'.$id,
                    'bs' => $this->bootstrap,
                    'style' => $this->style,
                    'seminar' => $seminar,
                    'user' => $user,
                ])
            );
        }
        else
        {

        }
    }
}